# Site settings
title: গ্রন্থালাপ
email: gronthalap@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  গ্রন্থালাপ ডট কম  বই ডকুমেন্টেশনের একটি স্বেচ্ছাসেবী উদ্যোগ। ২০১৭ সালে একটি মিডনাইট টক থেকে
  এই সাইটের সূচনা। সবাইকে নিয়ে আমরা এগিয়ে যাবো এটাই আমাদের প্রত্যাশা।
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://gronthalap.com" # the base hostname & protocol for your site
#twitter_username: JAlexBranham
#github_username:  jabranham
permalink: /:categories/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
