# Site settings
title: গ্রন্থালাপ
email: gronthalap@gmail.com
description: "আমাদের চোখে আমাদের বই"
logo_location: "https://placeholdit.imgix.net/~text?txtsize=30&bg=F8F8F8&txtclr=002E62&txt=LOGO&w=100&h=100"
permalink: /:categories/:title.html

# Build settings
markdown: kramdown
kramdown:
  input: GFM

highlighter: rouge

#Other Global Configuration
exclude: ['README.md']

excerpt_separator: <!--বাকিঅংশ পড়ুন-->

#show the jumbotron header on index page
show_blog_header: true
